AQAutosMVC/Models/AQAuto.cs
    
﻿using System.ComponentModel.DataAnnotations;

namespace AQAutosMVC.Models
{
    public class AQAuto
    {

        [Key]
        public int AQAutoID { get; set; }

        [Required]
        [StringLength(50)]
        public string? AQMarca { get; set; }

        public int AQAnio { get; set; }

        [StringLength(10)]
        public string? AQCombustible { get; set; }

        public bool AQUsado { get; set; }

        [Range(0.01, 9999)]
        public decimal AQPrecio { get; set; }

        [EmailAddress]
        public string? AqEmaildistribuidor { get; set; }

        public DateTime AQFechaIngreso { get; set; }

    }
}

AQAutosMVC/Models/ErrorViewModel.cs
namespace AQAutosMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AQAutosMVC/Controllers/AQAutoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AQAutosMVC.Models;

namespace AQAutosMVC.Controllers
{
    public class AQAutoesController : Controller
    {
        private readonly AQAutosContext _context;

        public AQAutoesController(AQAutosContext context)
        {
            _context = context;
        }

        // GET: AQAutoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.AQAuto.ToListAsync());
        }

        // GET: AQAutoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aQAuto = await _context.AQAuto
                .FirstOrDefaultAsync(m => m.AQAutoID == id);
            if (aQAuto == null)
            {
                return NotFound();
            }

            return View(aQAuto);
        }

        // GET: AQAutoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AQAutoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AQAutoID,AQMarca,AQAnio,AQCombustible,AQUsado,AQPrecio,AqEmaildistribuidor,AQFechaIngreso")] AQAuto aQAuto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aQAuto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aQAuto);
        }

        // GET: AQAutoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aQAuto = await _context.AQAuto.FindAsync(id);
            if (aQAuto == null)
            {
                return NotFound();
            }
            return View(aQAuto);
        }

        // POST: AQAutoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AQAutoID,AQMarca,AQAnio,AQCombustible,AQUsado,AQPrecio,AqEmaildistribuidor,AQFechaIngreso")] AQAuto aQAuto)
        {
            if (id != aQAuto.AQAutoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aQAuto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AQAutoExists(aQAuto.AQAutoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aQAuto);
        }

        // GET: AQAutoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aQAuto = await _context.AQAuto
                .FirstOrDefaultAsync(m => m.AQAutoID == id);
            if (aQAuto == null)
            {
                return NotFound();
            }

            return View(aQAuto);
        }

        // POST: AQAutoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aQAuto = await _context.AQAuto.FindAsync(id);
            if (aQAuto != null)
            {
                _context.AQAuto.Remove(aQAuto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AQAutoExists(int id)
        {
            return _context.AQAuto.Any(e => e.AQAutoID == id);
        }
    }
}

AQAutosMVC/Controllers/HomeController.cs
using AQAutosMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AQAutosMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AQAutosMVC/Views/AQAutoes/Create.cshtml
@model AQAutosMVC.Models.AQAuto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AQAuto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AQMarca" class="control-label"></label>
                <input asp-for="AQMarca" class="form-control" />
                <span asp-validation-for="AQMarca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AQAnio" class="control-label"></label>
                <input asp-for="AQAnio" class="form-control" />
                <span asp-validation-for="AQAnio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AQCombustible" class="control-label"></label>
                <input asp-for="AQCombustible" class="form-control" />
                <span asp-validation-for="AQCombustible" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AQUsado" /> @Html.DisplayNameFor(model => model.AQUsado)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="AQPrecio" class="control-label"></label>
                <input asp-for="AQPrecio" class="form-control" />
                <span asp-validation-for="AQPrecio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AqEmaildistribuidor" class="control-label"></label>
                <input asp-for="AqEmaildistribuidor" class="form-control" />
                <span asp-validation-for="AqEmaildistribuidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AQFechaIngreso" class="control-label"></label>
                <input asp-for="AQFechaIngreso" class="form-control" />
                <span asp-validation-for="AQFechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AQAutosMVC/Views/AQAutoes/Delete.cshtml
@model AQAutosMVC.Models.AQAuto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AQAuto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQMarca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQMarca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQAnio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQAnio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQCombustible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQCombustible)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQUsado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQUsado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQPrecio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQPrecio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AqEmaildistribuidor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AqEmaildistribuidor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQFechaIngreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQFechaIngreso)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AQAutoID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AQAutosMVC/Views/AQAutoes/Details.cshtml
@model AQAutosMVC.Models.AQAuto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AQAuto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQMarca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQMarca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQAnio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQAnio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQCombustible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQCombustible)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQUsado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQUsado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQPrecio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQPrecio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AqEmaildistribuidor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AqEmaildistribuidor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AQFechaIngreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AQFechaIngreso)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AQAutoID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AQAutosMVC/Views/AQAutoes/Edit.cshtml
@model AQAutosMVC.Models.AQAuto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>AQAuto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AQAutoID" />
            <div class="form-group">
                <label asp-for="AQMarca" class="control-label"></label>
                <input asp-for="AQMarca" class="form-control" />
                <span asp-validation-for="AQMarca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AQAnio" class="control-label"></label>
                <input asp-for="AQAnio" class="form-control" />
                <span asp-validation-for="AQAnio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AQCombustible" class="control-label"></label>
                <input asp-for="AQCombustible" class="form-control" />
                <span asp-validation-for="AQCombustible" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AQUsado" /> @Html.DisplayNameFor(model => model.AQUsado)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="AQPrecio" class="control-label"></label>
                <input asp-for="AQPrecio" class="form-control" />
                <span asp-validation-for="AQPrecio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AqEmaildistribuidor" class="control-label"></label>
                <input asp-for="AqEmaildistribuidor" class="form-control" />
                <span asp-validation-for="AqEmaildistribuidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AQFechaIngreso" class="control-label"></label>
                <input asp-for="AQFechaIngreso" class="form-control" />
                <span asp-validation-for="AQFechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AQAutosMVC/Views/AQAutoes/Index.cshtml
@model IEnumerable<AQAutosMVC.Models.AQAuto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AQMarca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AQAnio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AQCombustible)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AQUsado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AQPrecio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AqEmaildistribuidor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AQFechaIngreso)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AQMarca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AQAnio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AQCombustible)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AQUsado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AQPrecio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AqEmaildistribuidor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AQFechaIngreso)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AQAutoID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AQAutoID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AQAutoID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AQAutosMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AQAutosMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AQAutosMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AQAutosMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AQAutosMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse d-sm-inline-flex justify-content-between collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AQAutoes" >AQAutoes</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AQAutosMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>